query GetAccountList(
  $after: String!
  $bankId: ID
  $isActive: BoolBaseFilterLookup
) {
  accountRelay(
    order: { name: ASC }
    filters: { isActive: $isActive, bank: { id: { exact: $bankId } } }
    first: 100
    after: $after
  ) {
    totalCount
    edges {
      node {
        amount
        name
        currency
        bank {
          id
          name
        }
        lastUpdate
        id
        isActive
        firstAdded
        type
        firstTransaction
        lastTransaction
      }
      cursor
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}

query GetSimpleAccountList($bankId: ID) {
  accountRelay(
    filters: { bank: { id: { exact: $bankId } } }
    order: { name: ASC }
  ) {
    edges {
      node {
        id
        name
      }
    }
  }
}

query GetAccountDetail($accountId: ID) {
  accountRelay(filters: { bank: {}, id: { exact: $accountId } }) {
    edges {
      node {
        amount
        name
        currency
        bank {
          id
          name
        }
        lastUpdate
        id
        isActive
        firstAdded
        type
        firstTransaction
        lastTransaction
      }
    }
  }
}

mutation UpdateAccount($id: ID!, $name: String, $type: AccountType, $isActive: Boolean, $firstAdded: Boolean) {
  updateAccount(data: { id: $id, name: $name, type: $type, isActive: $isActive, firstAdded: $firstAdded }) {
    id
    name
    type
    isActive
    firstAdded
  }
}

query GetAccountType {
  __type(name: "AccountType") {
    enumValues {
      name
    }
  }
}

mutation CreateAccount($name: String!, $bankId: ID!, $type: AccountType, $currency: CurrencyType) {
  createAccount(data: { name: $name, bank: { set: $bankId }, type: $type, currency: $currency }) {
    id
    name
  }
}
