query CreditCards($first: Int = 100) {
  creditCardRelay(first: $first) {
    edges {
      node {
        id
        account {
          id
          name
          bank {
            id
            name
          }
          amount
          lastTransaction
          isActive
        }
        annualFee
        issueDate
        expiryDate
        notes
        benefits {
          id
          category
          title
          description
          rate
          capAmount
          conditions
        }
      }
    }
  }
}

query UnlinkedCreditCardAccounts($first: Int = 100) {
  accountRelay(
    filters: { type: { exact: CREDIT_CARD }, isActive: { exact: true }, bank: {} }
    first: $first
  ) {
    edges {
      node {
        id
        name
        bank {
          id
          name
        }
        amount
      }
    }
  }
}

mutation CreateCreditCard(
  $accountId: ID!
  $annualFee: Decimal
  $issueDate: Date
  $expiryDate: Date
  $notes: String! = ""
) {
  createCreditCard(
    data: {
      account: { set: $accountId }
      annualFee: $annualFee
      issueDate: $issueDate
      expiryDate: $expiryDate
      notes: $notes
    }
  ) {
    id
    account {
      id
      name
    }
    annualFee
  }
}
