query GetRetailerList($after: String) {
  retailerRelay(after: $after) {
    edges {
      node {
        id
        name
        category
      }
    }
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}

query GetRetailerType {
  __type(name: "RetailerType") {
    name
    enumValues {
      name
    }
  }
}

query GetAllRetailers($after: String) {
  retailerRelay(first: 100, after: $after) {
    edges {
      node {
        id
        name
        category
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
