query GetStockTransaction($id: ID!) {
  stockTransactionRelay(
    filters: { stock: {}, account: { bank: {} }, id: { exact: $id } }
    first: 1
  ) {
    edges {
      node {
        id
        date
        price
        amount
        shares
        balance
        note
        stock {
          id
          ticker
          name
          currency
        }
        account {
          id
          name
          currency
          bank {
            name
          }
        }
        relatedTransaction {
          id
          date
          amount
          type
          retailer {
            name
          }
        }
      }
    }
  }
}

query GetStockList {
  stockRelay {
    edges {
      node {
        id
        ticker
        name
        currency
      }
    }
    totalCount
  }
}

query GetAllStocks {
  stockRelay(first: 500) {
    edges {
      node {
        id
        ticker
        name
        currency
      }
    }
  }
}

query GetAccountStockTransactions($accountId: ID, $after: String, $first: Int) {
  stockTransactionRelay(
    filters: { stock: {}, account: { bank: {}, id: { exact: $accountId } } }
    order: { date: DESC }
    first: $first
    after: $after
  ) {
    edges {
      node {
        id
        date
        price
        amount
        shares
        balance
        note
        stock {
          id
          ticker
          name
          currency
        }
        relatedTransaction {
          id
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
    totalCount
  }
}

mutation UpdateStockTransaction($id: ID!, $relatedTransactionId: ID) {
  updateStockTransaction(
    data: { id: $id, relatedTransaction: { set: $relatedTransactionId } }
  ) {
    id
    relatedTransaction {
      id
    }
  }
}

mutation CreateStock($name: String!, $ticker: String, $currency: CurrencyType) {
  createStock(data: { name: $name, ticker: $ticker, currency: $currency }) {
    id
    name
    ticker
    currency
  }
}

query GetStockPrices($stockId: ID!, $first: Int, $after: String) {
  stockPriceRelay(
    filters: { stock: { id: { exact: $stockId } } }
    order: { date: DESC }
    first: $first
    after: $after
  ) {
    edges {
      node {
        id
        date
        price
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
    totalCount
  }
}

mutation CreateStockPrice($stockId: ID!, $date: Date!, $price: Decimal!) {
  createStockPrice(data: { stock: { set: $stockId }, date: $date, price: $price }) {
    id
    date
    price
  }
}

mutation CreateStockTransaction(
  $date: Date!
  $accountId: ID!
  $stockId: ID!
  $price: Decimal!
  $amount: Decimal!
  $shares: Decimal!
  $note: String
) {
  createStockTransaction(
    data: {
      date: $date
      account: { set: $accountId }
      stock: { set: $stockId }
      price: $price
      amount: $amount
      shares: $shares
      note: $note
    }
  ) {
    id
    price
    amount
    shares
    note
  }
}
