query GetAllTransactions($after: String, $first: Int, $accountId: ID, $dateGte: Date, $dateLte: Date) {
  transactionRelay(
    first: $first
    after: $after
    filters: {
      account: { bank: {}, id: { exact: $accountId } }
      date: { gte: $dateGte, lte: $dateLte }
    }
    order: { date: DESC, amount: ASC }
  ) {
    edges {
      cursor
      node {
        id
        amount
        balance
        date
        isInternal
        reviewed
        requiresDetail
        type
        note
        retailer {
          id
          name
          type
          category
        }
        account {
          id
          name
          currency
          bank {
            name
          }
        }
      }
    }
    totalCount
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}

query GetRetailerDetail($retailerId: ID) {
  retailerRelay(filters: { id: { exact: $retailerId } }) {
    edges {
      node {
        id
        name
        category
      }
    }
  }
}

query GetTransactionList($accountId: ID, $first: Int, $after: String) {
  transactionRelay(
    filters: { account: { bank: {}, id: { exact: $accountId } } }
    order: { date: DESC, amount: ASC, balance: ASC }
    first: $first
    after: $after
  ) {
    edges {
      cursor
      node {
        id
        amount
        balance
        date
        isInternal
        requiresDetail
        reviewed
        note
        type
        relatedTransaction {
          id
        }
        retailer {
          id
          name
        }
      }
    }
    totalCount
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
  accountRelay(filters: { bank: {}, id: { exact: $accountId } }) {
    edges {
      node {
        currency
      }
    }
  }
}

query GetTransactionCategory {
  __type(name: "TransactionCategory") {
    name
    enumValues {
      name
    }
  }
}

query GetLastTransactionDate {
  transactionRelay(first: 1, order: { id: DESC }) {
    edges {
      node {
        date
      }
    }
  }
}

query GetUnreviewedTransactions($first: Int!, $after: String!, $dateGte: Date, $dateLte: Date) {
  transactionRelay(
    first: $first
    after: $after
    filters: {
      account: { bank: {} }
      reviewed: { exact: false }
      date: { gte: $dateGte, lte: $dateLte }
    }
    order: { date: DESC, id: DESC }
  ) {
    edges {
      cursor
      node {
        id
        amount
        date
        isInternal
        requiresDetail
        reviewed
        type
        note
        retailer {
          id
          name
        }
        account {
          id
          name
          currency
          bank {
            name
          }
        }
      }
    }
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}

query GetTransaction($id: ID) {
  transactionRelay(filters: { id: { exact: $id }, account: { bank: {} } }, first: 1) {
    edges {
      node {
        id
        amount
        balance
        date
        isInternal
        reviewed
        requiresDetail
        type
        note
        retailer {
          id
          name
        }
        account {
          id
          name
          currency
          bank {
            name
          }
        }
      }
    }
  }
}
